In [2]:
pip install twilio

  Obtaining dependency information for twilio from https://files.pythonhosted.org/packages/38/01/5374f240380907bcd9ba676c9d5f0b3ed85fd6e8d6f6dcc29280942c132e/twilio-8.8.0-py2.py3-none-any.whl.metadata
  Obtaining dependency information for aiohttp>=3.8.4 from https://files.pythonhosted.org/packages/21/4e/452858698e53ddf06ea137eac268db535c9605394c27236f9986168dd82f/aiohttp-3.8.5-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
    --------------------------------------- 0.0/1.8 MB 1.3 MB/s eta 0:00:02
   - -------------------------------------- 0.1/1.8 MB 812.7 kB/s eta 0:00:03
   - -------------------------------------- 0.1/1.8 MB 653.6 kB/s eta 0:00:03
   - -------------------------------------- 0.1/1.8 MB 653.6 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/1.8 MB 552.2 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/1.8 MB 841.6 kB/s eta 0:00:02
   ------ --------------------------------- 0.3/1

In [37]:
import pandas as pd #for reading dataset
import numpy as np # array handling functions
import os
from twilio.rest import Client


account_sid = 'AC635e331b3dc8ef7a11db5b43188775f6'
auth_token = '0993237dfe91524279a3378737027934'
client1 = Client(account_sid, auth_token)
def sms(a):
    ch='your cholesterol level is '+str(a)
    message = client1.messages \
              .create(
                  body=ch,
                  from_='+12232173795',
                  to='+919443456184'
                  )
    print(message.sid)
    message = client1.messages \
              .create(
                  body=ch,
                  from_='+12232173795',
                  to='+917904571252'
                  )
    print(message.sid)
    message = client1.messages \
              .create(
                  body=ch,
                  from_='+12232173795',
                  to='+918778349167'
                  )
    print(message.sid)


In [7]:
dataset = pd.read_csv(r"C:\Users\Snekalatha\Downloads\dataset_2190_cholesterol.csv")#reading dataset
print(dataset) # printing dataset

     age  sex  cp  trestbps  fbs  restecg  thalach  exang  oldpeak  slope ca  \
0     63    1   1       145    1        2      150      0      2.3      3  0   
1     67    1   4       160    0        2      108      1      1.5      2  3   
2     67    1   4       120    0        2      129      1      2.6      2  2   
3     37    1   3       130    0        0      187      0      3.5      3  0   
4     41    0   2       130    0        2      172      0      1.4      1  0   
..   ...  ...  ..       ...  ...      ...      ...    ...      ...    ... ..   
298   45    1   1       110    0        0      132      0      1.2      2  0   
299   68    1   4       144    1        0      141      0      3.4      2  2   
300   57    1   4       130    0        0      115      1      1.2      2  1   
301   57    0   2       130    0        2      174      0      0.0      2  1   
302   38    1   3       138    0        0      173      0      0.0      1  ?   

    thal  num  chol  
0      6    0   2

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   fbs       303 non-null    float64
 5   restecg   303 non-null    float64
 6   thalach   303 non-null    float64
 7   exang     303 non-null    float64
 8   oldpeak   303 non-null    float64
 9   slope     303 non-null    float64
 10  ca        303 non-null    object 
 11  thal      303 non-null    object 
 12  num       303 non-null    int64  
 13  chol      303 non-null    int64  
dtypes: float64(10), int64(2), object(2)
memory usage: 33.3+ KB


In [18]:
dataset.replace({'?':0 }, inplace=True)

In [19]:
for column in dataset.columns:
    if dataset.columns.dtype=='object':
        dataset[column] = dataset[column].astype('int64')

In [20]:
x = dataset.iloc[:,:-1].values #locating inputs
y = dataset.iloc[:,-1].values #locating outputs
#printing X and Y
print("x=",x)
print("y=",y)


x= [[63  1  1 ...  0  6  0]
 [67  1  4 ...  3  3  2]
 [67  1  4 ...  2  7  1]
 ...
 [57  1  4 ...  1  7  3]
 [57  0  2 ...  1  3  1]
 [38  1  3 ...  0  3  0]]
y= [233 286 229 250 204 236 268 354 254 203 192 294 256 263 199 168 229 239
 275 266 211 283 284 224 206 219 340 226 247 167 239 230 335 234 233 226
 177 276 353 243 225 199 302 212 330 230 175 243 417 197 198 177 290 219
 253 266 233 172 273 213 305 177 216 304 188 282 185 232 326 231 269 254
 267 248 197 360 258 308 245 270 208 264 321 274 325 235 257 216 234 256
 302 164 231 141 252 255 239 258 201 222 260 182 303 265 188 309 177 229
 260 219 307 249 186 341 263 203 211 183 330 254 256 407 222 217 282 234
 288 239 220 209 258 227 204 261 213 250 174 281 198 245 221 288 205 309
 240 243 289 250 308 318 298 265 564 289 246 322 299 300 293 277 197 304
 214 248 255 207 223 288 282 160 269 226 249 394 212 274 233 184 315 246
 274 409 244 270 305 195 240 246 283 254 196 298 247 294 211 299 234 236
 244 273 254 325 126 313 211 309 25

In [21]:
from sklearn.model_selection import train_test_split # for splitting dataset
x_train,x_test,y_train,y_test = train_test_split(x ,y, test_size = 0.25 ,random_state = 0)
#printing the spliited dataset
print("x_train=",x_train)
print("x_test=",x_test)
print("y_train=",y_train)
print("y_test=",y_test)

x_train= [[62  0  4 ...  0  3  0]
 [58  0  2 ...  2  3  3]
 [57  1  4 ...  1  6  1]
 ...
 [35  0  4 ...  0  3  0]
 [50  1  4 ...  0  7  4]
 [59  0  4 ...  0  3  1]]
x_test= [[ 34   0   2 118   0   0 192   0   0   1   0   3   0]
 [ 67   0   3 115   0   2 160   0   1   2   0   7   0]
 [ 54   1   4 110   0   2 108   1   0   2   1   3   3]
 [ 64   0   4 180   0   0 154   1   0   1   0   3   0]
 [ 44   1   4 112   0   2 153   0   0   1   1   3   2]
 [ 67   1   4 120   0   0  71   0   1   2   0   3   2]
 [ 57   1   4 152   0   0  88   1   1   2   1   7   1]
 [ 35   1   4 126   0   2 156   1   0   1   0   7   1]
 [ 53   1   4 123   0   0  95   1   2   2   2   7   3]
 [ 46   0   4 138   0   2 152   1   0   2   0   3   0]
 [ 56   1   4 125   1   2 144   1   1   2   1   3   1]
 [ 55   0   2 135   0   2 161   0   1   2   0   3   0]
 [ 64   0   4 130   0   0 122   0   2   2   2   3   0]
 [ 56   1   3 130   1   2 142   1   0   2   1   6   2]
 [ 57   1   3 150   0   0 174   0   1   1   0   3   0]
 [

In [28]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)#trainig Algorithm

DecisionTreeClassifier()

In [29]:
y_pred=classifier.predict(x_test) #testing model
print("y_pred",y_pred) # predicted output


y_pred [157 277 286 201 247 267 184 172 178 236 208 196 243 256 239 197 288 197
 342 269 245 167 253 327 271 342 407 253 267 258 294 240 180 212 193 198
 198 236 335 234 325 273 253 239 226 335 246 199 239 269 239 269 239 269
 234 269 298 215 269 311 234 235 199 188 218 309 326 184 298 277 234 275
 233 275 205 294]


In [30]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_pred, y_test)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.03


In [31]:
a1=float(input("ENTER THE AGE= "))
b1=float(input("ENTER THE SEX= "))
c1=float(input("ENTER THE CP= "))
d1=float(input("ENTER THE TRESTBPS= "))
e1=float(input("ENTER THE FBS= "))
f1=float(input("ENTER THE REST ECG= "))
g1=float(input("ENTER THE THALACH= "))
h1=float(input("ENTER THE EXANG= "))
i1=float(input("ENTER THE OLD PEAK= "))
j1=float(input("ENTER THE SLOPE= "))
k1=float(input("ENTER THE CA= "))
l1=float(input("ENTER THE THAL= "))
m1=float(input("ENTER THE NUM= "))
##
a = classifier.predict([[a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1]])
print('Predicted new output value: %s' % (a))


ENTER THE AGE= 45
ENTER THE SEX= 1
ENTER THE CP= 45
ENTER THE TRESTBPS= 64
ENTER THE FBS= 67
ENTER THE REST ECG= 24
ENTER THE THALACH= 65
ENTER THE EXANG= 24
ENTER THE OLD PEAK= 25
ENTER THE SLOPE= 87
ENTER THE CA= 35
ENTER THE THAL= 24
ENTER THE NUM= 26
Predicted new output value: [178]


In [38]:
sms(a)

TwilioRestException: HTTP 400 error: Unable to create record: The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.